site_name: Subzero
copyright: Â© 2018 Square, Inc.
nav:
    - Learn: index.md
    - Physical components: physical_components.md
    - Software components: software_components.md
    - Supply chain security: supply_chain_security.md
    - Initialization:
      - HSM initialization: hsm_initialization.md
      - Wallet initialization: wallet_initialization.md
    - Transactions:
      - Sample transaction: sample_transaction.md
      - Address derivation: address_derivation.md
      - Signing ceremony: signing_ceremony.md
      - Merging signatures: merging_signatures.md
    - Audit: audit.md
    - Bug Bounty: bug_bounty.md
    - Contributors: contributors.md
    - Contributing: contributing.md
    - License: license.md
theme: readthedocs
extra_css:
    - extra_css.css
